name: agendaki
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  flutter_dotenv: ^5.0.2
  firebase_auth: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    - lib/assets/images/agendak3.jpeg

=======
  - assets/images/agendak3.png
>>>>>>> Stashed changes
=======
  - assets/images/agendak3.png
>>>>>>> Stashed changes
